
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?defined_class (STR(?defined_class__label) AS ?defined_class_label) ?structure (STR(?structure__label) AS ?structure_label) (STR(?structure__match_property) AS ?structure_match_property)
WHERE {
?defined_class <http://www.w3.org/2000/01/rdf-schema#label> ?_v0 .
FILTER(isIRI(?defined_class))
FILTER(REGEX(?_v0, "\\Qpart of \\E(.+)\\Q\\E"))
BIND((REPLACE(?_v0, "\\Qpart of \\E(.+)\\Q\\E", "$1")) AS ?_v1)
VALUES ?structure__match_property { <http://www.w3.org/2000/01/rdf-schema#label> }
?structure ?structure__match_property ?_v1 .
?defined_class <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?_v2 .
FILTER(isIRI(?defined_class))
FILTER(REGEX(?_v2, "\\Q$synonym\\E"))
?defined_class <http://www.w3.org/2000/01/rdf-schema#seeAlso> ?_v3 .
FILTER(isIRI(?defined_class))
FILTER(REGEX(?_v3, "\\Q$synonym\\E"))
?defined_class rdfs:subClassOf ?_v4 .
FILTER(isIRI(?defined_class))
?_v4 owl:onProperty <http://purl.obolibrary.org/obo/BFO_0000050> .
?_v4 owl:someValuesFrom ?structure .
FILTER(isIRI(?structure))
OPTIONAL { ?defined_class rdfs:label ?defined_class__label . }
OPTIONAL { ?structure rdfs:label ?structure__label . }
}
ORDER BY ?defined_class_label
